### ISSUE TITLE
CT ERROR: Assertion failed: MigrationReport problem: propertyValidValueNoLongerSupported 

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale-basics#58]
```
ph-scale-basics : migration : 1.6->main : assert
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/phet-io-wrappers/migration/?sim=ph-scale-basics&oldVersion=1.6&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale-basics%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1727290723124%22%2C%22timestamp%22%3A1727291341421%7D
ERROR: Assertion failed: MigrationReport problem: propertyValidValueNoLongerSupported 

 {
  "stateSchemaIncompatible": [],
  "initialStatesAreIncompatible": [],
  "propertyValidValueNoLongerSupported": [
    {
      "phetioID": "phScaleBasics.general.model.localeProperty",
      "missingValue": "ar_KW"
    }
  ],
  "switchedFromInvalidValueToNewDefault": [
    "phScaleBasics.general.model.localeProperty"
  ],
  "phetioIDNotInNewAPI": [],
  "notStatefulAnymore": [],
  "incompletePhetioElementRenames": [],
  "incompletePhetioElementDeletes": [],
  "processedNothing": [],
  "newNeededIOTypes": {},
  "relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
  "missingStringPhetioElements": []
}
 [object Object]
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/assert/js/assert.js:45:13
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/assert/js/assert.js:45:13)
    at assert (MigrationReport.ts:168:22)
    at reportForContext (MigrationEngine.ts:86:22)
    at migrate (StandardPhetioWrapper.ts:281:37)
    at loadStandardPhetioWrapperFromHTML (PhetioClient.ts:1495:38)
    at onBothStudiosLoaded/< (http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/phet-io-wrappers/migration/migration.js:227:66)
    at EventListener.handleEvent*onBothStudiosLoaded (http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/phet-io-wrappers/migration/migration.js:223:12)
    at <unknown> (http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/phet-io-wrappers/migration/migration.js:107:11)
    at EventListener.handleEvent* (http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/phet-io-wrappers/migration/migration.js:89:10)
    at async* (http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/phet-io-wrappers/migration/migration.js:277:4)
====================
FULL LOG:
[URL] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1727290723124%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dph-scale-basics%26oldVersion%3D1.6%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22ph-scale-basics%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1727290723124%22%2C%22timestamp%22%3A1727291341421%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1727290723124%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dph-scale-basics%26oldVersion%3D1.6%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22ph-scale-basics%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1727290723124%22%2C%22timestamp%22%3A1727291341421%7D
[ATTACHED] 
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/phet-io-wrappers/migration/?sim=ph-scale-basics&oldVersion=1.6&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale-basics%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1727290723124%22%2C%22timestamp%22%3A1727291341421%7D
[ATTACHED] 
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/studio/?sim=ph-scale-basics&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale-basics%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1727290723124%22%2C%22timestamp%22%3A1727291341421%7D&phetioMigrationReport=assert&fuzz&locales=*
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/ph-scale-basics/ph-scale-basics_en.html?brand=phet-io&ea&postMessageOnError&sim=ph-scale-basics&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale-basics%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1727290723124%22%2C%22timestamp%22%3A1727291341421%7D&phetioMigrationReport=assert&fuzz&locales=*&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1727290723124/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[NAVIGATED] https://phet-io.colorado.edu/sims/ph-scale-basics/1.6/wrappers/studio/?phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale-basics%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1727290723124%22%2C%22timestamp%22%3A1727291341421%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/ph-scale-basics/1.6/ph-scale-basics_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale-basics%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1727290723124%22%2C%22timestamp%22%3A1727291341421%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "https://phet-io.colorado.edu/sims/ph-scale-basics/1.6/ph-scale-basics_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale-basics%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1727290723124%22%2C%22timestamp%22%3A1727291341421%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false" line: 16805}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "https://phet-io.colorado.edu/sims/ph-scale-basics/1.6/ph-scale-basics_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale-basics%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1727290723124%22%2C%22timestamp%22%3A1727291341421%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false" line: 16805}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "https://phet-io.colorado.edu/sims/ph-scale-basics/1.6/ph-scale-basics_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale-basics%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1727290723124%22%2C%22timestamp%22%3A1727291341421%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false" line: 16805}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "https://phet-io.colorado.edu/sims/ph-scale-basics/1.6/ph-scale-basics_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale-basics%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1727290723124%22%2C%22timestamp%22%3A1727291341421%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false" line: 16805}]
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed:  MigrationReport problem: propertyValidValueNoLongerSupported 

 {
  "stateSchemaIncompatible": [],
  "initialStatesAreIncompatible": [],
  "propertyValidValueNoLongerSupported": [
    {
      "phetioID": "phScaleBasics.general.model.localeProperty",
      "missingValue": "ar_KW"
    }
  ],
  "switchedFromInvalidValueToNewDefault": [
    "phScaleBasics.general.model.localeProperty"
  ],
  "phetioIDNotInNewAPI": [],
  "notStatefulAnymore": [],
  "incompletePhetioElementRenames": [],
  "incompletePhetioElementDeletes": [],
  "processedNothing": [],
  "newNeededIOTypes": {},
  "relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
  "missingStringPhetioElements": []
} JSHandle@object
[CONSOLE] continuous-test-wrapper-error
[PAGE ERROR] Error: Assertion failed: MigrationReport problem: propertyValidValueNoLongerSupported 

 {
  "stateSchemaIncompatible": [],
  "initialStatesAreIncompatible": [],
  "propertyValidValueNoLongerSupported": [
    {
      "phetioID": "phScaleBasics.general.model.localeProperty",
      "missingValue": "ar_KW"
    }
  ],
  "switchedFromInvalidValueToNewDefault": [
    "phScaleBasics.general.model.localeProperty"
  ],
  "phetioIDNotInNewAPI": [],
  "notStatefulAnymore": [],
  "incompletePhetioElementRenames": [],
  "incompletePhetioElementDeletes": [],
  "processedNothing": [],
  "newNeededIOTypes": {},
  "relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
  "missingStringPhetioElements": []
}
 [object Object]

id: "Sparky Node Firefox"
Snapshot from 9/25/2024, 12:58:43 PM
```

**Comment by pixelzoom** [comment]
This first appeared in CT this morning, 9/25/24 @ 3:59:03 AM MT.

**Comment by pixelzoom** [comment]
@samreid volunteered to have a look (thanks!) and made the above commits, which seem to have eliminated the problem. 

@samreid can you please describe why https://github.com/phetsims/phet-io-wrappers/commit/7b9a1ca79e397fd20bd42203448a8c99bbc6299f was necessary, and why it was only failing for ph-scale-basics?  Then this issue can probably be closed.

**Comment by samreid** [comment]
A newly submitted translation will appear in the old API as a locale `validValue`. If a developer runs the migration wrapper before regenerating `grunt generate-phet-io-api` new new simulation will not have the new translation the API as a `validValue`. The migration wrapper leverages the API file on disk for the new one, and we didn't want a translator adding a new translation to break things or force a `grunt generate-phet-io-api`, so as we have done elsewhere in API comparison, we opt out of the validValues check for locales. This is a general solution and we believe this issue can be closed.
